yatube/about/urls.py
from django.urls import path

from . import views

app_name = "about"

urlpatterns = [
    path("author/", views.AboutAuthorView.as_view(), name="author"),
    path("tech/", views.AboutTechView.as_view(), name="tech"),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = "posts"

urlpatterns = [
    path("", views.index, name="index"),
    path("group/<slug:slug>/", views.group_posts, name="group_list"),
    path("profile/<str:username>/", views.profile, name="profile"),
    path("posts/<int:post_id>/", views.post_detail, name="post_detail"),
    path("create/", views.post_create, name="post_create"),
    path("posts/<int:post_id>/edit/", views.post_edit, name="post_edit"),
    path(
        "posts/<int:post_id>/comment/", views.add_comment, name="add_comment"
    ),
    path("follow/", views.follow_index, name="follow_index"),
    path(
        "profile/<str:username>/follow/",
        views.profile_follow,
        name="profile_follow",
    ),
    path(
        "profile/<str:username>/unfollow/",
        views.profile_unfollow,
        name="profile_unfollow",
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("posts.urls", namespace="posts")),
    path("auth/", include("users.urls", namespace="users")),
    path("about/", include("about.urls", namespace="about")),
    path("admin/", admin.site.urls),
    path("auth/", include("django.contrib.auth.urls")),
]

handler404 = "core.views.page_not_found"
handler500 = "core.views.server_error"
handler403 = "core.views.permission_denied"

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models


User = get_user_model()


class Group(models.Model):

    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="posts",
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name="posts",
    )
    image = models.ImageField("Картинка", upload_to="posts/", blank=True)

    class Meta:
        ordering = ("-pub_date",)

    def __str__(self):
        return self.text


class Comment(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name="comments"
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name="Автор",
        related_name="comments",
    )
    text = models.TextField(
        "Текст комментария", help_text="Введите текст комментария"
    )
    created = models.DateTimeField(
        "Дата публикации комментария", auto_now_add=True
    )

    class Meta:
        ordering = ("-created",)


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="follower",
        verbose_name="Подписчик",
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="following",
        verbose_name="Автор",
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["user", "author"], name="unique_following"
            )
        ]

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = (
            "text",
            "group",
            "image",
        )
        labels = {
            "text": "Текст поста",
            "group": "Группа",
            "image": "Картинка",
        }
        help_texts = {
            "text": "Текст нового поста",
            "group": "Группа, к которой будет относиться пост",
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = {"text"}
        labels = {"text": "Текст"}

yatube/posts/views.py
from django.shortcuts import get_object_or_404, redirect
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpRequest

from .models import Group, Post, User, Comment, Follow
from .forms import PostForm, CommentForm
from .utils import paginate


def index(request: HttpRequest) -> HttpResponse:
    posts = Post.objects.select_related("author", "group")

    page_number = request.GET.get("page")
    page_obj = paginate(page_number, posts)

    context = {
        "page_obj": page_obj,
        "index": True,
    }
    return render(request, "posts/index.html", context)


def group_posts(request: HttpRequest, slug: str) -> HttpResponse:
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.select_related("author")

    page_number = request.GET.get("page")
    page_obj = paginate(page_number, posts)

    context = {
        "group": group,
        "page_obj": page_obj,
    }
    return render(request, "posts/group_list.html", context)


def profile(request: HttpRequest, username: str) -> HttpResponse:
    author = get_object_or_404(User, username=username)

    post_list = author.posts.all()

    page_number = request.GET.get("page")
    page_obj = paginate(page_number, post_list)
    following = (
        request.user.is_authenticated
        and Follow.objects.filter(user=request.user, author=author).exists()
    )

    count_user_posts = author.posts.count()

    context = {
        "author": author,
        "count_user_posts": count_user_posts,
        "page_obj": page_obj,
        "following": following,
    }
    return render(request, "posts/profile.html", context)


def post_detail(request: HttpRequest, post_id: int) -> HttpResponse:
    post = get_object_or_404(Post, id=post_id)
    author = post.author

    author_posts_count = author.posts.count()

    comments = Comment.objects.filter(post_id=post_id)
    form = CommentForm()

    context = {
        "post": post,
        "author_posts_count": author_posts_count,
        "form": form,
        "comments": comments,
    }
    return render(request, "posts/post_detail.html", context)


@login_required
def post_create(request: HttpRequest) -> HttpResponse:
    form = PostForm(request.POST or None)

    if not form.is_valid():
        return render(request, "posts/create_post.html", {"form": form})

    form.instance.author = request.user
    form.save()
    return redirect("posts:profile", request.user.username)


@login_required
def post_edit(request: HttpRequest, post_id: int) -> HttpResponse:
    post = get_object_or_404(Post, id=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post,
    )

    if post.author != request.user:
        return redirect("posts:post_detail", post_id)

    template = "posts/create_post.html"
    context = {
        "form": form,
        "is_edit": True,
    }

    if not form.is_valid():
        return render(request, template, context)

    form.save()
    return redirect("posts:post_detail", post_id=post.id)


@login_required
def add_comment(request: HttpRequest, post_id: int) -> HttpResponse:
    form = CommentForm(request.POST or None)
    post = get_object_or_404(Post, id=post_id)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect("posts:post_detail", post_id=post_id)


@login_required
def follow_index(request: HttpRequest) -> HttpResponse:
    """Функция генерирует страницу с постами авторов,
    на которых подписан пользователь."""
    template = "posts/follow.html"
    posts_list = Post.objects.filter(author__following__user=request.user)
    page_obj = paginate(request, posts_list)
    context = {"page_obj": page_obj, "follow": True}
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    """Функция для подписки на авторов."""
    template = "posts:profile"
    author = get_object_or_404(User, username=username)
    user = request.user
    if user != author:
        Follow.objects.get_or_create(user=user, author=author)
    return redirect(template, username=author.username)


@login_required
def profile_unfollow(request, username):
    """Функция для отписок."""
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=author).delete()
    return redirect("posts:profile", username=username)

yatube/templates/posts/article.html
{% load thumbnail %}

<article>
  <ul>
    <li>
      Автор:
      {% if post.author.get_full_name %}
        {{ post.author.get_full_name }}
      {% else %}
        {{ post.author }}
      {% endif %}
      <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
    </li>
    <li>Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
  </ul>
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
  <img class="card-img my-2" src="{{ im.url }}">
{% endthumbnail %}
<p>
  {{ post.text }}
</p>
<a href="{% url "posts:post_detail" post.id %}">подробная информация</a>
</article>

yatube/templates/posts/create_post.html
{% extends 'base.html' %}

{% block title %}
  {% if is_edit %}
    Редактировать пост
  {% else %}
    Новый пост
  {% endif %}
{% endblock %}

{% block content %}
  {% load thumbnail %}

  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            {% if is_edit %}
              Редактировать пост
            {% else %}
              Новый пост
            {% endif %}
          </div>
          <div class="card-body">
            {% load user_filters %}

            {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}<div class="alert alert-danger">{{ field.label }} {{ error|escape }}</div>{% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}<div class="alert alert-danger">{{ error|escape }}</div>{% endfor %}
            {% endif %}
            <form method="post"
                  enctype="multipart/form-data"
                  {% if is_edit %} action="{% url 'posts:post_edit' form.instance.id %}" method="post" {% else %} action="{% url 'posts:post_create' %}" method="post" {% endif %}>
              {% csrf_token %}
              {% for field in form %}
                <div class="form-group row my-3 p-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                    {% if field.field.required %}<span class="required text-danger">*</span>{% endif %}
                  </label>
                  {{ field }}
                  <small>{{ field.help_text }}</small>
                </div>
              {% endfor %}
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}

{% block title %}Избранные авторы.{% endblock %}

{% block content %}
  {% load thumbnail %}

  <div class="container py-5">
    <h1>Избранные авторы.</h1>
    {% include 'posts/includes/switcher.html' %}

    {% for post in page_obj %}
      <ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <li>
        Автор: {{ post.author.get_full_name }}
        <a href="{% url 'posts:profile' post.author %}">все записи автора</a>
      </li>
      <li>Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
    </ul>
    <p>
      {{ post.text }}
    </p>
    {% if post.group_id is not None %}
      <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}

{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}

{% block title %}Записи сообщества {{ group.title }}{% endblock %}

{% block content %}
  <div class="container py-5">
    <h1>{{ group.title }}</h1>
    <p>
      {{ group.description }}
    </p>
    {% for post in page_obj %}
      {% include 'posts/article.html' %}

      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}

  </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}Последние обновления на сайте.{% endblock %}

{% block content %}
  {% load cache %}

  <div class="container py-5">
    <h1>Последние обновления на сайте.</h1>
    {% cache 20 index_page %}
    {% include 'posts/includes/switcher.html' %}

    {% for post in page_obj %}
      {% include 'posts/article.html' %}

      {% if post.group %}
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
      {% endif %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
  {% endcache %}
  {% include 'posts/includes/paginator.html' %}

</div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block title %}Пост {{ post|truncatechars:30 }}{% endblock %}

{% block content %}
  {% load user_filters %}
  {% load thumbnail %}

  <main>
    <div class="container py-4">
      <div class="row">
        <aside class="col-12 col-md-4">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
            {% if post.group %}
              <li class="list-group-item">
                Группа: {{ post.group }}
                <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
              </li>
            {% endif %}
            <li class="list-group-item">Автор: {{ post.author.get_full_name }} {{ post.author.username }}</li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора: <span >{{ author_posts_count }}</span>
            </li>
            <li class="list-group-item">
              <a href="{% url "posts:profile" post.author %}">все посты пользователя</a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-8">
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>
          {{ post.text }}
        </p>
        {% if user.username == post.author.username %}
          <a class="btn btn-primary" href="{% url "posts:post_edit" post.id %}">Редактировать запись</a>
        {% endif %}
        {% for field in form %}
          {% if user.is_authenticated %}
            <div class="card my-4">
              <h5 class="card-header">Добавить комментарий:</h5>
              <div class="card-body">
                <form method="post" action="{% url 'posts:add_comment' post.id %}">
                  {% csrf_token %}
                  <div class="form-group mb-2">{{ form.text|addclass:"form-control" }}</div>
                  <button type="submit" class="btn btn-primary">Отправить</button>
                </form>
              </div>
            </div>
          {% endif %}
        {% endfor %}
        {% for comment in comments %}
          <div class="media mb-4">
            <div class="media-body">
              <h5 class="mt-0">
                <a href="{% url 'posts:profile' comment.author.username %}">{{ comment.author.username }}</a>
              </h5>
              <p>
                {{ comment.text }}
              </p>
            </div>
          </div>
        {% endfor %}
      </article>
    </div>
  </div>
</main>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}

{% block title %}Профайл пользователя {{ author.get_full_name }}{% endblock %}

{% block content %}
  <main>
    <div class="container py-5">
      <div class="mb-5">
        <h1>Все посты пользователя {{ author.get_full_name }}</h1>
        <h3>Всего постов: {{ count_user_posts }}</h3>
        {% if following %}
          <a class="btn btn-lg btn-light"
             href="{% url 'posts:profile_unfollow' author.username %}"
             role="button">Отписаться</a>
        {% else %}
          <a class="btn btn-lg btn-primary"
             href="{% url 'posts:profile_follow' author.username %}"
             role="button">Подписаться</a>
        {% endif %}
        {% for post in page_obj %}
          {% include 'posts/article.html' %}

          {% if post.group %}
            <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
          {% endif %}
          {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
        {% include 'posts/includes/paginator.html' %}

      </div>
    </main>
  {% endblock %}